# -*- coding: utf-8 -*-
"""Movie_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPuX_BanNd-eJei67JiAzU80X7iD4XIf
"""

import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df=pd.read_csv("/content/movies.csv")
df

df.isnull().sum()

feature = ["genres","keywords","tagline","cast","director"]

for i in feature:
  df[i] = df[i].fillna("")

combined_feature = df["genres"] + " " +  df["keywords"] + " " + df["tagline"] + " " +df["cast"] + " " +df["director"]

tdidf = TfidfVectorizer()

vec = tdidf.fit_transform(combined_feature)

"""Cosine Similarity"""

similarity = cosine_similarity(vec)

print(similarity)

similarity.shape

movie_name = input("Enter the Movie name : ")

title_list = df["title"].tolist()
print(title_list)

"""Movies recommendation system"""

movie_name = input("Enter movie name to get suggestion: ")

movie_title = df["title"].tolist()

find_match = difflib.get_close_matches(movie_name, title_list)

movie_index = df[df.title == find_match[0]]["index"].values[0]

similarity_score = list(enumerate(similarity[movie_index]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print("Movies for you: \n")
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = df[df.index==index]["title"].values[0]
  if (i<30):
    print(i," ",title_from_index)
    i+=1

